apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
    name: aws-config-iam
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
        eks.amazonaws.com/role-arn: arn:aws:iam::754022411271:role/iam_crossplane_role
spec:
    podSecurityContext:
        fsGroup: 2000
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
    name: aws-provider-iam
spec:
    credentials:
        source: IRSA
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "2"
    name: provider-aws-iam
spec:
    package: xpkg.upbound.io/upbound/provider-aws-iam:v1.2.0
    controllerConfigRef:
        name: aws-config-iam

