apiVersion: v1
kind: Secret
metadata:
  name: spin-operator
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  enableOCI: "true"
  name: "spin-operator"
  project: "default"
  type: "helm"
  url: "ghcr.io/nginxinc/charts"
