apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kwasm-operator
spec:
  project: default
  source:
    repoURL: http://kwasm.sh/kwasm-operator/
    chart: kwasm-operator
    targetRevision: 0.16.0  # Specify the desired version
  destination:
    server: https://kubernetes.default.svc  # In-cluster Kubernetes API server
    namespace: kwasm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  values: |
    kwasmOperator:
      installerImage: "ghcr.io/spinkube/containerd-shim-spin/node-installer:v0.16.0"
