apiVersion: v1
kind: Namespace
metadata:
  name: spin-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spin-operator
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/spinkube/charts
    chart: spin-operator
    targetRevision: "0.4.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: spin-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true