apiVersion: v1
kind: Namespace
metadata:
    name: nginx-gateway-fabric
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nginx-fabric-gateway
spec:
    destination:
        namespace: 'nginx-gateway-fabric'
        server: 'https://kubernetes.default.svc'
    source:
        repoURL: ghcr.io/nginxinc/charts
        targetRevision: 1.1.0
        chart: nginx-gateway-fabric
    sources: []
    project: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
