apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "3"
    name: external-dns
    namespace: external-dns
    labels:
        app.kubernetes.io/name: external-dns
spec:
    strategy:
        type: Recreate
    selector:
        matchLabels:
            app.kubernetes.io/name: external-dns
    template:
        metadata:
            labels:
                app.kubernetes.io/name: external-dns
        spec:
            serviceAccountName: external-dns
            containers:
                - name: external-dns
                  image: registry.k8s.io/external-dns/external-dns:v0.14.0
                  args:
                      - --source=service
                      - --source=ingress
                      - --domain-filter=systekeks.no # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
                      - --provider=aws
                      - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
                      - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
                      - --registry=txt
                      - --txt-owner-id=external-dns
                  env:
                      - name: AWS_DEFAULT_REGION
                        value: eu-west-1 # change to region where EKS is installed
