apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    name: eks-demo-route53-policy
spec:
    forProvider:
        policy: |
            {
                "Version": "2012-10-17",
                "Statement": [
                {
                    "Effect": "Allow",
                    "Action": [
                        "route53:ChangeResourceRecordSets"
                    ],
                    "Resource": [
                        "arn:aws:route53:::hostedzone/*"
                    ]
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "route53:ListHostedZones",
                        "route53:ListResourceRecordSets",
                        "route53:ListTagsForResource"
                    ],
                    "Resource": [
                        "*"
                    ]
                }
            ]
            }
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: systek.no/v1alpha1
kind: IRSABinding
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    name: external-dns-role-binding
    namespace: external-dns
spec:
    roleName: external-dns-role
    serviceAccount: "system:serviceaccount:external-dns:external-dns"
    rolePolicyArn: "arn:aws:iam::754022411271:policy/AllowExternalDNSUpdates"
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: external-dns
    namespace: external-dns
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::754022411271:role/external-dns-role
    labels:
        app.kubernetes.io/name: external-dns