apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
    annotations:
        meta.upbound.io/example-id: iam/v1beta1/rolepolicy
    labels:
        testing.upbound.io/example-name: s3-role
    name: s3-role
spec:
    forProvider:
        assumeRolePolicy: |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "arn:aws:iam::754022411271:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/6042C964265029341FC0F0808E03B472"
                    },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                    "StringLike": {
                        "oidc.eks.eu-west-1.amazonaws.com/id/6042C964265029341FC0F0808E03B472:sub": "system:serviceaccount:crossplane-system:provider-aws-s3*"
                    }
                }
            }
            ]}
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
    annotations:
        meta.upbound.io/example-id: iam/v1beta1/role
    labels:
        testing.upbound.io/example-name: role
    name: s3-policy-attachment
spec:
    forProvider:
        policyArn: arn:aws:iam::aws:policy/AmazonS3FullAccess
        roleSelector:
            matchLabels:
                testing.upbound.io/example-name: s3-role
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
    name: aws-config-s3
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::754022411271:role/crossplans3test
spec:
    podSecurityContext:
        fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: provider-aws-s3
    namespace: crossplane-system
spec:
    package: xpkg.upbound.io/upbound/provider-aws-s3:v1.1.0
    controllerConfigRef:
        name: aws-config-s3
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: aws-provider-s3
spec:
    credentials:
        source: IRSA
