apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.15.0
    chart: crossplane
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
    name: aws-config-s3
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::754022411271:role/crossplans3test
spec:
    podSecurityContext:
        fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: provider-aws-s3
    namespace: crossplane-system
spec:
    package: xpkg.upbound.io/upbound/provider-aws-s3:v1.1.0
    controllerConfigRef:
        name: aws-config-s3
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: aws-provider-s3
spec:
    credentials:
        source: IRSA