apiVersion: systek.no/v1alpha1
kind: IRSABinding
metadata:
    name: s3-provider-role-binding
spec:
    roleName: s3-provider-role
    serviceAccount: "system:serviceaccount:crossplane-system:provider-aws-s3*"
    rolePolicyArn: "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
    name: aws-config-s3
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::754022411271:role/s3-role
spec:
    podSecurityContext:
        fsGroup: 2000
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: provider-aws-s3
    namespace: crossplane-system
spec:
    package: xpkg.upbound.io/upbound/provider-aws-s3:v1.1.0
    controllerConfigRef:
        name: aws-config-s3
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: aws-provider-s3
spec:
    credentials:
        source: IRSA
