apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.15.0
    chart: crossplane
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
    name: provider-aws-s3
    namespace: crossplane-system
spec:
    package: xpkg.upbound.io/upbound/provider-aws-s3:v1.1.0