apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
    name: function-systek-iam
spec:
    package: 754022411271.dkr.ecr.eu-west-1.amazonaws.com/systek-related-stuff:0.0.8
    runtimeConfigRef:
        name: modify-service-account
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
    name: function-auto-ready
spec:
    package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
    name: modify-service-account
spec:
    serviceAccountTemplate:
        metadata:
            name: function-systek-iam
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: crossplane-system
    name: configmaps-get-role
rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: configmaps-get-rolebinding
    namespace: crossplane-system
subjects:
    - kind: ServiceAccount
      name: function-systek-iam
      namespace: crossplane-system
roleRef:
    kind: Role
    name: configmaps-get-role
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
    name: compositeirsabindings.systek.no
spec:
    group: systek.no
    names:
        kind: CompositeIRSABinding
        plural: compositeirsabindings
        singular: compositeirsabinding
    claimNames:
        kind: IRSABinding
        plural: irsabindings
        singular: irsabinding
    versions:
        - name: v1alpha1
          served: true
          referenceable: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              roleName:
                                  type: string
                              serviceAccount:
                                  type: string
                              rolePolicyArn:
                                  type: string
                              providerConfigRef:
                                  type: object
                                  properties:
                                      name:
                                          type: string
                  status:
                      type: object
                      properties:
                          roleArn:
                              type: string

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
    name: function-systek-iam
spec:
    compositeTypeRef:
        apiVersion: systek.no/v1alpha1
        kind: CompositeIRSABinding
    mode: Pipeline
    pipeline:
        - step: create-role-and-binding
          functionRef:
              name: function-systek-iam
        - step: automatically-detect-readiness
          functionRef:
              name: function-auto-ready