resources:
    - argocd-repositories.yaml
    - crossplane.yaml
    - crossplane-iam-provider.yaml
    - external-dns/deployment.yaml
    - external-secrets.yaml
    - nginx-gateway-fabric.yaml
    - irsa-composition.yaml
    - crossplane-s3-provider.yaml
    - external-dns/namespace.yaml
    - external-dns/sa.yaml
    - external-dns/roles.yaml
    - external-dns/deployment.yaml