apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.nginx.com/stable'
    targetRevision: '0.17.1'  
    chart: nginx-ingress
    helm:
      parameters: 
        - name: controller.replicaCount
          value: "1"
        - name: controller.service.type
          value: "LoadBalancer"
  destination:
    server: 'https://kubernetes.default.svc'  
    namespace: nginx-ingress  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

