apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: '4.9.1'
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.replicaCount
          value: "1"
        - name: controller.service.type
          value: "LoadBalancer"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
