apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
spec:
  destination:
    namespace: nginx-ingress
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: ghcr.io/nginxinc/charts
    targetRevision: 1.1.2
    chart: nginx-ingress
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
