apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: example
    namespace: external-secrets
spec:
    refreshInterval: 1h
    secretStoreRef:
        name: cluster-secret-store
        kind: ClusterSecretStore
    target:
        name: demo-secret-to-be-created
        creationPolicy: Owner
    data:
        - secretKey: TEST
          remoteRef:
              key: test-secret
              property: TEST