apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.14
    chart: external-secrets
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
