apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: systek.no/v1alpha1
kind: IRSABinding
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    name: external-secrets-role-binding
    namespace: external-secrets
spec:
    roleName: external-secrets-role
    serviceAccount: "system:serviceaccount:external-secrets:external-secrets"
    rolePolicyArn: "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: extern
    targetRevision: 0.9.14
    chart: external-secrets
    helm:
        values: |
            serviceAccount:
                  annotations: { "eks.amazonaws.com/role-arn": "arn:aws:iam::754022411271:role/external-secrets-role" }
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
