---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    chart: cert-manager
    helm:
        values: |
            installCRDs: true
            config:
                apiVersion: controller.config.cert-manager.io/v1alpha1
                kind: ControllerConfiguration
                featureGates:
                    ExperimentalGatewayAPISupport: true

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
