apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    name: eks-demo-route53-cert-manager-policy
spec:
    forProvider:
        policy: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": "route53:GetChange",
                  "Resource": "arn:aws:route53:::change/*"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "route53:ChangeResourceRecordSets",
                    "route53:ListResourceRecordSets"
                  ],
                  "Resource": "arn:aws:route53:::hostedzone/*"
                }
              ]
            }
    providerConfigRef:
        name: aws-provider-iam
---
apiVersion: systek.no/v1alpha1
kind: IRSABinding
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    name: cert-manager-dns-role-binding
    namespace: external-secrets
spec:
    roleName: cert-manager-dns-role
    serviceAccount: "system:serviceaccount:cert-manager:cert-manager"
    rolePolicyArn: "arn:aws:iam::754022411271:policy/eks-demo-route53-cert-manager-policy"
    providerConfigRef:
        name: aws-provider-iam
---